name: kiemthucongdiem

on:
  push:
    branches: ["main]          #chay code len nhanh main

jobs:
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      -name: buoc 1 - xin chao
      run: echo "hello hutech"

      -name: buoc 2 - tai code
      run: actions/checkout@v6

      -name: buoc 3 - doc file
      run: cat README.md 





