name: testbai
on:
  push:
    branches: ["main"]

jobs:
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: buoc 1- xin caho
        run: echo "hello hutech"

      - name: buoc2
        uses: actions/checkout@v6

      - name: buoc 3
        run: cat README.md
        
